@startuml

actor admin

' Эндпоинты сервиса А
!$A_Create_User = "POST /users"
!$A_Get_User = "GET /users/{id}"

' Эндпоинты сервиса B
!$B_Create_Role = "Post /roles"
!$B_Get_Role = "GET /roles/{id}"


autonumber

admin->A: $A_Create_User
admin->A: $A_Get_User


admin->B: $B_Create_Role
admin->B: $B_Get_Role

@enduml