@startuml

autonumber

box "Маркетплейсы" #LightBlue
actor Order_Provider order 10
end box

box "Заказы"  #Business
control Order_service order 20
database Order_database order 30
control Payment_service order 40
database Payment_database order 50
end box

queue message_broker order 60

box "ПВЗ"
control PVZ_service order 70
database PVZ_database order 80
end box


Order_Provider->Order_service: создай заказ
Order_service->Order_database: Создаем заказ в БД

Order_service-->Payment_service: Создать задачу на оплату заказа
Payment_service->Payment_database: создаем задачу \nна оплату в БД
Payment_service-->Order_service: задача создана

Order_service->message_broker: отправка команды на создание заказа в ПВЗ

Order_service-->Order_Provider: заказ создан


PVZ_service->message_broker: Получение сообщения \nиз кафки
PVZ_service->PVZ_database: создаем заказ в БД


legend
 ..**Условные обозначения**..
|**Название компонента**| **Краткое описание**|
| Order_Provider | [[http://example.com Маркетплейсы, поставляющие заказы]] |
| Order_service | [[http://example.com Сервис, отвечающий за обработку заказов]] |
| Order_database | [[http://example.com БД Order_service]]|
| Payment_service | [[http://example.com Сервис, отвечающий за обработку платежей по заказам]] |
| Payment_database | [[http://example.com БД Payment_service]] |
| message_broker | [[http://example.com Описание топиков и контрактов]] |
| PVZ_service | [[http://example.com Сервис, отвечающий за выдачу заказов в ПВЗ]] |
| PVZ_database | [[http://example.com БД PVZ_service]] |
end legend



@enduml
